### ISSUE TITLE
当前Project中的[release]的不是一个有效的AWS资源

### ISSUE THREAD

**Issue by Ruvikm** [haifennj/AWSIdeaPlugin#1]
请问一下这个报错是什么原因呢，我根目录改成release了

**Comment by haifennj** [comment]
你好，这个插件是为一个特定产品开发的，请先了解：https://www.awspaas.com/support，release是产品的默认目录名称。

**Comment by Ruvikm** [comment]
感谢回复，我和同事对了一下目录，目录中没有其他的东西，我是按你们的配置文档配置的，唯一不同是你们用的是19版本的IDEA新建的JavaEE项目，能否在官网补充一下用IDEA 2022版本配置环境的教程呢，不胜感激（因为22版IDEA新建项目，会多生成一个以项目名为名的文件夹，选择直接导入“release”文件夹，也可以配置完启动平台但是插件使用不了）

**Comment by haifennj** [comment]
不好意思，由于新版本的IDEA的api有很大调整，经历有限，暂时未支持高版本的适配，建议使用19或者20版本，后期插件更新也会限制一下最高版本，抱歉

**Comment by Ruvikm** [comment]
了解了解，非常感谢您的回复
